// Placeholder product catalog. Replace with your real 50 SKUs.
export type Product = { sku: string; name: string; category: string };

export const PRODUCTS: Product[] = [
  { sku: 'NV-CAL-D3', name: 'Neovit Calcium + D3 (20 effervescent tablets)', category: 'Bones & Joints' },
  { sku: 'NV-MULTI', name: 'Neovit Multivitamin Complex', category: 'Daily Wellness' },
  { sku: 'NV-VITC-1000', name: 'Neovit Vitamin C 1000mg Effervescent', category: 'Immunity' },
  { sku: 'NV-VITD3-2000', name: 'Neovit Vitamin D3 2000 IU', category: 'Immunity' },
  { sku: 'NV-MAG-B6', name: 'Neovit Magnesium + B6', category: 'Energy & Stress' },
  { sku: 'NV-ZINC', name: 'Neovit Zinc 25mg', category: 'Immunity' },
  { sku: 'NV-IRON', name: 'Neovit Iron + Folic Acid', category: 'Women\'s Health' },
  { sku: 'NV-OMEGA3', name: 'Neovit Omega-3 1000mg', category: 'Heart & Brain' },
  { sku: 'NV-COQ10', name: 'Neovit Coenzyme Q10 100mg', category: 'Heart & Brain' },
  { sku: 'NV-BCOMPLEX', name: 'Neovit Vitamin B Complex', category: 'Energy & Stress' },
  { sku: 'NV-COLLAGEN', name: 'Neovit Marine Collagen + Vitamin C', category: 'Skin & Beauty' },
  { sku: 'NV-BIOTIN', name: 'Neovit Biotin 5000mcg', category: 'Skin & Beauty' },
  { sku: 'NV-HAIR', name: 'Neovit Hair, Skin & Nails Formula', category: 'Skin & Beauty' },
  { sku: 'NV-PROBIO', name: 'Neovit Probiotic 10 Strains', category: 'Digestive Health' },
  { sku: 'NV-FIBER', name: 'Neovit Daily Fiber Powder', category: 'Digestive Health' },
  { sku: 'NV-GINGER', name: 'Neovit Ginger Extract', category: 'Digestive Health' },
  { sku: 'NV-TURMERIC', name: 'Neovit Turmeric + Black Pepper', category: 'Joints & Inflammation' },
  { sku: 'NV-GLUCOSA', name: 'Neovit Glucosamine + Chondroitin', category: 'Joints & Inflammation' },
  { sku: 'NV-MSM', name: 'Neovit MSM 1500mg', category: 'Joints & Inflammation' },
  { sku: 'NV-MELAT', name: 'Neovit Melatonin 1mg', category: 'Sleep & Relaxation' },
  { sku: 'NV-VALER', name: 'Neovit Valerian Root', category: 'Sleep & Relaxation' },
  { sku: 'NV-ASHWA', name: 'Neovit Ashwagandha 600mg', category: 'Energy & Stress' },
  { sku: 'NV-GINSENG', name: 'Neovit Ginseng Extract', category: 'Energy & Stress' },
  { sku: 'NV-GREENT', name: 'Neovit Green Tea Extract', category: 'Weight Management' },
  { sku: 'NV-LCARN', name: 'Neovit L-Carnitine 1000mg', category: 'Weight Management' },
  { sku: 'NV-GARCINIA', name: 'Neovit Garcinia Cambogia', category: 'Weight Management' },
  { sku: 'NV-CLA', name: 'Neovit CLA Softgels', category: 'Weight Management' },
  { sku: 'NV-WHEY', name: 'Neovit Whey Protein Vanilla', category: 'Sports Nutrition' },
  { sku: 'NV-BCAA', name: 'Neovit BCAA 2:1:1', category: 'Sports Nutrition' },
  { sku: 'NV-CREAT', name: 'Neovit Creatine Monohydrate', category: 'Sports Nutrition' },
  { sku: 'NV-PREWO', name: 'Neovit Pre-Workout Booster', category: 'Sports Nutrition' },
  { sku: 'NV-ELECT', name: 'Neovit Electrolyte Effervescent', category: 'Sports Nutrition' },
  { sku: 'NV-LUTEIN', name: 'Neovit Lutein + Zeaxanthin', category: 'Eye Health' },
  { sku: 'NV-BLUEB', name: 'Neovit Blueberry Eye Complex', category: 'Eye Health' },
  { sku: 'NV-PRENATAL', name: 'Neovit Prenatal Multivitamin', category: 'Women\'s Health' },
  { sku: 'NV-MENOPAUSE', name: 'Neovit Menopause Support', category: 'Women\'s Health' },
  { sku: 'NV-MENS', name: 'Neovit Men\'s Daily Multi', category: 'Men\'s Health' },
  { sku: 'NV-PROSTATE', name: 'Neovit Prostate Support', category: 'Men\'s Health' },
  { sku: 'NV-KIDS-MULTI', name: 'Neovit Kids Multivitamin Gummies', category: 'Children' },
  { sku: 'NV-KIDS-D3', name: 'Neovit Kids Vitamin D3 Drops', category: 'Children' },
  { sku: 'NV-KIDS-OMEGA', name: 'Neovit Kids Omega-3 Gummies', category: 'Children' },
  { sku: 'NV-IMMUNE', name: 'Neovit Immune Boost Complex', category: 'Immunity' },
  { sku: 'NV-ECHIN', name: 'Neovit Echinacea Extract', category: 'Immunity' },
  { sku: 'NV-PROPOLIS', name: 'Neovit Propolis Throat Spray', category: 'Immunity' },
  { sku: 'NV-LIVER', name: 'Neovit Liver Detox Milk Thistle', category: 'Detox' },
  { sku: 'NV-CRAN', name: 'Neovit Cranberry Extract', category: 'Urinary Health' },
  { sku: 'NV-SAW', name: 'Neovit Saw Palmetto', category: 'Men\'s Health' },
  { sku: 'NV-CHARC', name: 'Neovit Activated Charcoal', category: 'Detox' },
  { sku: 'NV-SPIRU', name: 'Neovit Spirulina 500mg', category: 'Superfoods' },
  { sku: 'NV-CHLOR', name: 'Neovit Chlorella Tablets', category: 'Superfoods' },
];
